### ISSUE TITLE
report the data to table `ss_node_ip`

### ISSUE THREAD

**Issue by ssrpanel** [ColetteContreras/v2ray-ssrpanel-plugin#13]
Hi, can your set the node auto report the data to the table `ss_node_ip`.
Table struct:
```
CREATE TABLE `ss_node_ip` (
	`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
	`node_id` INT(11) NOT NULL DEFAULT '0' COMMENT '节点ID',
	`port` INT(11) NOT NULL DEFAULT '0' COMMENT '端口',
	`type` CHAR(10) NOT NULL DEFAULT 'tcp' COMMENT '类型：tcp、udp' COLLATE 'utf8mb4_unicode_ci',
	`ip` TEXT NULL COMMENT '连接IP：每个IP用,号隔开' COLLATE 'utf8mb4_unicode_ci',
	`created_at` INT(11) NOT NULL DEFAULT '0' COMMENT '上报时间',
	PRIMARY KEY (`id`),
	INDEX `idx_node` (`node_id`),
	INDEX `idx_port` (`port`)
) COLLATE='utf8mb4_unicode_ci' ENGINE=InnoDB;
```

**Comment by ssrpanel** [comment]
every 60 seconds (or it can be configurable in config files)  auto insert all uuid 's connecting IP, i will add a new field  `uuid` in this table for v2ray

**Comment by ColetteContreras** [comment]
Why not user_id?

**Comment by ColetteContreras** [comment]
I haven't seen your database changes, you may have to add an identity field first!

I use this link to find whether you added or not. https://github.com/ssrpanel/SSRPanel/search?q=ss_node_ip&unscoped_q=ss_node_ip

**Comment by ssrpanel** [comment]
Yeah...u r right.

**Comment by ssrpanel** [comment]
oh no , just need the field `port` , cause i indetity different user by the `port`,

**Comment by ssrpanel** [comment]
and the `port` will auto relate to table `user` 's field `port` , by the ORM

**Comment by ssrpanel** [comment]
hi, i will add a new field `user_id` in table `ss_node_ip`

**Comment by ColetteContreras** [comment]
Hi,

I've just finished the work, report user ip list to the table, `ss_node_ip`. I'm not sure about that it will works as you wanted.  Here is the PR, #19, could you test it before my publishing?

**Comment by ssrpanel** [comment]
@ColetteContreras 
Hi, it not works

**Comment by ColetteContreras** [comment]
Sorry about that i haven't give you the documentation.

1. update config.json

```
  "stats": {
    "trackIp": true
  }
```

2. download and unpack v2ray and v2ctl

could you try it again?

**Comment by samac08** [comment]
i have new test 2.0.6  @ssrpanel @ColetteContreras 
Test Results:: 
-----2个用户测试,在线,IP上报正常,但是ssrp适配有问题----

0.前提,仅显示一行数据信息,多个用户在线同样这样显示一行.
1.所有在线用户均不显示用户名(显示【用户已删除】). 
2不能第二行显示第二个账户信息,永远现是这一行
3.断开第一个用户后,才显示第二个用户的信息.并且还是在这一行显示,并且不显示用户名. 
4.用户在线IP选项不显示ip,十分钟后显示?
<img src="https://s2.ax1x.com/2019/03/03/kLTwQK.png" alt="kLTwQK.png" border="0">
<img src="https://s2.ax1x.com/2019/03/03/kLT0sO.png" alt="kLT0sO.png" border="0">
<img src="https://s2.ax1x.com/2019/03/03/kLTaz6.png" alt="kLTaz6.png" border="0">

**Comment by dawfds** [comment]
这里上报的端口是零，胖虎大佬的数据库查询方式是应该以端口为条件，所以显示用户已删除

**Comment by samac08** [comment]
> Sorry about that i haven't give you the documentation.
> 
> 1. update config.json
> 
> ```
>   "stats": {
>     "trackIp": true
>   }
> ```
> 1. download and unpack v2ray and v2ctl
> 
> could you try it again?
--------------------------------------------------------------
@ColetteContreras @ssrpanel 
I found that 2.0.6 does not display ip correctly, can not be identified by ssrpanel
The problem is that 2.0.6 does not upload the user port number.
Ssrpanel uses the user port instead of the user id to identify the user's online information.
No user port information causes ssrpanel to display an exception and the user is not recognized.
To fix this, you need to upload the user port at the same time.
I have manually added port information in the sql table,
After adding the port, ssrpanel shows normal. The problem is solved perfectly.

<img src="https://s2.ax1x.com/2019/03/12/AiEdF1.png" alt="AiEdF1.png" border="0">
<img src="https://s2.ax1x.com/2019/03/12/AiENw9.png" alt="AiENw9.png" border="0">
